apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-controller-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: csi-vultr-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-vultr-provisioner-role
  apiGroup: rbac.authorization.k8s.io
