repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  # rev: v4.5.0
  rev: c4a0b883114b00d8d76b479c820ce7950211c99b
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: end-of-file-fixer
  - id: forbid-submodules
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  # rev: v0.9.0.6
  rev: 4de1378e4cd853bfc2b111b05fff35e2dbf809a3
  hooks:
  - id: shellcheck
- repo: https://github.com/tekwizely/pre-commit-golang
  # rev: v1.0.0-rc.1
  rev: 302c7fd28cdbb62d5fd1e3965fe36e33a5f77803
  hooks:
  - id: go-fmt
- repo: https://github.com/antonbabenko/pre-commit-terraform
  # rev: v1.85.0
  rev: ef906bcaab574ac94b79de96d52093d0c033cb45
  hooks:
  - id: terraform_checkov
    args:
    - '--args=--quiet'
  - id: terraform_fmt
  - id: terraform_providers_lock
  - id: terraform_tflint
    args:
    - '--args=--module'
  - id: terraform_trivy
  - id: terraform_validate
  - id: terrascan
    files: ^terraform/.*$
