apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vultr-block-storage
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  block_type: high_perf

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vultr-block-storage-retain
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  block_type: high_perf

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vultr-block-storage-hdd
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  block_type: storage_opt

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vultr-block-storage-hdd-retain
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  block_type: storage_opt
