apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns
          args:
            - --source=service
            - --zone-id-filter=$(CF_ZONE_ID)
            - --provider=cloudflare
          env:
            - name: CF_API_EMAIL
              valueFrom:
                secretKeyRef:
                  name: tf-cloudflare
                  key: "email"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tf-cloudflare
                  key: "token"
            - name: CF_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: tf-cloudflare
                  key: "zone_id"
