apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.14.0

resources:
  - deployment.yml
  - secret.yml
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
