apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler
rules:
  - apiGroups: ['']
    resources: ['services', 'endpoints', 'pods']
    verbs: ['get', 'watch', 'list']
  - apiGroups:  ['']
    resources: ['nodes']
    verbs: ['watch', 'list']