apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  annotations:
    "external-dns.alpha.kubernetes.io/endpoints-type": HostIP
    "external-dns.alpha.kubernetes.io/hostname": api.example.com
    "external-dns.alpha.kubernetes.io/cloudflare-proxied": true
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8000
